### ISSUE TITLE
Create one entry point for all widgets

### ISSUE THREAD

**Issue by niquola** [HealthSamurai/suitkin#1]
It would be nice to have a one entry point for all widgets:

```clj
(require '[suitking.core :as sui])

[sui/button ...]
[sui/input ...]
```

**Comment by Panthevm** [comment]
https://github.com/HealthSamurai/suitkin/blob/2fe71295050357b06f524cc5cc404accaf918dd0/src/suitkin/core.cljc#L1-L7
